version: '3.5'

services:
  db:
    image: postgres
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/data_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
